In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('Luxury_Housing_Bangalore (1).csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [5]:
df.describe()

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [6]:
df.shape

(101000, 18)

## MISSING VALUE REPLACEMENT

In [7]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [8]:
us=df['Unit_Size_Sqft'].median()

In [9]:
df['Unit_Size_Sqft'].fillna(us, inplace=True)

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\95982183.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Unit_Size_Sqft'].fillna(us, inplace=True)

In [10]:
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [11]:
df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].median(), inplace=True)

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\1775130773.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].median(), inplace=True)

In [12]:
df['Amenity_Score'].fillna(df['Amenity_Score'].mean(), inplace=True)

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\1969309245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amenity_Score'].fillna(df['Amenity_Score'].mean(), inplace=True)

In [13]:
df['Buyer_Comments'].fillna("No Comments", inplace=True)

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\4037927286.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Buyer_Comments'].fillna("No Comments", inplace=True)

In [14]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

## Booking Flag,Price_per_Sqft,Quarter_Number Derivation

In [34]:
df['Booking_Flag'] = df['Possession_Status'].str.strip().str.lower().map({
    'ready to move': 1,
    'launch': 1,
    'under construction': 0
})

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\1455027536.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Booking_Flag'] = df['Possession_Status'].str.strip().str.lower().map({

In [28]:
df['Price_per_Sqft']=df['Ticket_Price_Cr']*1000000/df['Unit_Size_Sqft']

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\1814713316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price_per_Sqft']=df['Ticket_Price_Cr']*1000000/df['Unit_Size_Sqft']

In [29]:
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\965793235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])

In [30]:
df['Quarter_Number'] = 'Q' + df['Purchase_Quarter'].dt.quarter.astype(str)

C:\Users\yadun\AppData\Local\Temp\ipykernel_32372\2105008881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quarter_Number'] = 'Q' + df['Purchase_Quarter'].dt.quarter.astype(str)

In [41]:
df.rename(columns={'Developer_Name': 'Builder'}, inplace=True)

In [42]:
df

,Property_ID,Micro_Market,Project_Name,Builder,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Booking_Flag,Price_per_Sqft,Quarter_Number
0,PROP000001,sarjapur road,Project_0,rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,1,3167.912059,Q1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.503663,Under construction,NRI Desk,no,7.723898,106,No Comments,0,2828.498589,Q2
2,PROP000003,bannerghatta road,Project_2,tata housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,1,1364.697601,Q4
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,1,1517.501210,Q1
4,PROP000005,koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,0,2147.109619,Q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,l&t realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,7.503663,Under construction,Online,yes,8.378800,109,Underpriced for location.,0,1835.169999,Q4
99996,PROP099997,yelahanka,Project_496,l&t realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,1,3870.098012,Q4
99997,PROP099998,rajajinagar,Project_497,prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No Comments,1,2452.255516,Q3
99998,PROP099999,indiranagar,Project_498,snn raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Comments,0,1411.602967,Q3
99999,PROP100000,hennur road,Project_499,embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No Comments,1,2076.478635,Q3

In [43]:
df['Property_ID'].duplicated().sum()

np.int64(0)

In [44]:
df = df.drop_duplicates(subset='Property_ID')

In [45]:
df['Builder'] = df['Builder'].str.lower()
df['Micro_Market'] = df['Micro_Market'].str.lower()

In [24]:
df

,Property_ID,Micro_Market,Project_Name,Builder,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Booking_Flag,Price_per_Sqft,Quarter_Number
0,PROP000001,sarjapur road,Project_0,rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,0,3167.912059,Q1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.503663,Under construction,NRI Desk,no,7.723898,106,No Comments,0,2828.498589,Q2
2,PROP000003,bannerghatta road,Project_2,tata housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,0,1364.697601,Q4
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,0,1517.501210,Q1
4,PROP000005,koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,0,2147.109619,Q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,l&t realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,7.503663,Under construction,Online,yes,8.378800,109,Underpriced for location.,0,1835.169999,Q4
99996,PROP099997,yelahanka,Project_496,l&t realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,0,3870.098012,Q4
99997,PROP099998,rajajinagar,Project_497,prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No Comments,0,2452.255516,Q3
99998,PROP099999,indiranagar,Project_498,snn raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Comments,0,1411.602967,Q3
99999,PROP100000,hennur road,Project_499,embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No Comments,0,2076.478635,Q3

In [46]:
Cleaned_df=df

In [47]:
Cleaned_df

,Property_ID,Micro_Market,Project_Name,Builder,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Booking_Flag,Price_per_Sqft,Quarter_Number
0,PROP000001,sarjapur road,Project_0,rmz,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,1,3167.912059,Q1
1,PROP000002,indiranagar,Project_1,puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.503663,Under construction,NRI Desk,no,7.723898,106,No Comments,0,2828.498589,Q2
2,PROP000003,bannerghatta road,Project_2,tata housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,1,1364.697601,Q4
3,PROP000004,bellary road,Project_3,embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,1,1517.501210,Q1
4,PROP000005,koramangala,Project_4,snn raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,0,2147.109619,Q4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,l&t realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,7.503663,Under construction,Online,yes,8.378800,109,Underpriced for location.,0,1835.169999,Q4
99996,PROP099997,yelahanka,Project_496,l&t realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,1,3870.098012,Q4
99997,PROP099998,rajajinagar,Project_497,prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No Comments,1,2452.255516,Q3
99998,PROP099999,indiranagar,Project_498,snn raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Comments,0,1411.602967,Q3
99999,PROP100000,hennur road,Project_499,embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No Comments,1,2076.478635,Q3

In [ ]:
import mysql.connector as connector
mydb = connector.connect(
        host = "localhost",
        user = "root",
        password = "Password@1",
        database = "Luxuryhousing",
        autocommit = True )
mycursor = mydb.cursor()
print(mydb)

In [ ]:
from sqlalchemy import create_engine
import pandas as pd  # Make sure pandas is imported

# Assuming 'Data' is your DataFrame that needs to be defined
# If you don't have it defined, you need to create or load it first
# For example:
# Data = pd.read_csv('your_data.csv')  # Uncomment and modify if needed

# Create the database engine with error handling
try:
    engine = create_engine(
        "mysql+pymysql://root:Password%401@localhost:3306/Luxuryhousing"
    )
    
    # Test the connection before attempting to write data
    connection = engine.connect()
    connection.close()
    
    # Write data to SQL with error handling
    Data.to_sql(
        "HousingData",
        con=engine,
        if_exists="append",
        index=False,
        # Optional: You can specify dtypes if there are type mismatches
        # dtype={"column_name": sqlalchemy.types.String(length=50)}
    )
    
    print("Data inserted successfully")
    
except Exception as e:
    print(f"Error occurred: {e}")